### ISSUE TITLE
Rapture 2.0.0-M3 SBT artifact issues

### ISSUE THREAD

**Issue by pvillega** [propensive/rapture#46] opened 2016-01-10 19:45 UTC
When adding Rapture to a sbt project:

```
libraryDependencies += "com.propensive" %% "rapture" % "2.0.0-M3" 
```

Sbt complains about not being able to resolve `"rapture-json-lift_2.11"`. Excluding that dependency fixes the issue.

```
libraryDependencies += "com.propensive" %% "rapture" % "2.0.0-M3" exclude("com.propensive","rapture-json-lift_2.11")
```

The Sbt project file is very basic, see below, so I don't expect this happening due to some archaic/fancy Sbt setting:

```
name := """stockfighter"""

version := "1.0"

scalaVersion := "2.11.7"

// load config in a declarative way
libraryDependencies += "com.github.melrief" %% "pureconfig" % "0.1.5"

libraryDependencies += "org.spire-math" %% "cats" % "0.3.0"

// Provides http client and json parser on top of Circe. Exclude json-lift due to errors in resolving dependency
libraryDependencies += "com.propensive" %% "rapture" % "2.0.0-M3" exclude("com.propensive","rapture-json-lift_2.11")

// Json parsing
libraryDependencies ++= Seq(
  "io.circe" %% "circe-core" % "0.2.1",
  "io.circe" %% "circe-generic" % "0.2.1",
  "io.circe" %% "circe-parse" % "0.2.1"
)

libraryDependencies += "org.scalatest" %% "scalatest" % "2.2.4" % "test"
```

**Comment by propensive** [comment] 2016-01-11 08:38
Thanks, @pvillega. The issue is, I think, related to a strange situation where Sonatype rejected publishing of `rapture-json-lift` (without an error). Lift was commented out of the build, but it appears like the dependency still remains.

I'll investigate reinstating Lift JSON as the solution to this.

**Comment by propensive** [comment] 2016-01-11 08:41
`json-lift` is referenced by `json-test`, which seems to be how it's still in the dependency list.

An alternative fix, I think, especially if you're just using Rapture JSON, is to depend only on the backend you're using, i.e.

```
"com.propensive" %% "rapture-json-circe" % "2.0.0-M3"
```

**Comment by propensive** [comment] 2016-01-11 08:43
Just opened issue about Rapture JSON Lift: https://github.com/propensive/rapture/issues/48

**Comment by pvillega** [comment] 2016-01-11 10:00
I'm playing around with Http and Json so I import the full Rapture. I'll add the exclusion by now as it works, hope it's not too painful to fix ;)

**Comment by propensive** [comment] 2016-02-06 19:04
I'm going to call this a duplicate of #48, as that is the cause of this effect.

**Closed as completed by propensive** 2016-02-06 19:04 UTC
Labels: build
