### ISSUE TITLE
Mark the old repos as deprecated

### ISSUE THREAD

**Issue by PerWiklander** [propensive/rapture#35] opened 2016-01-03 00:20 UTC
It looks like the old 'one repo per module' repos have been abandoned in favor for this single rapture repo. Please make that clear with a big NOTICE at the top of the readme of the other repos. I spent some hours trying to get the old rapture.i18n working in scala.js today... :-(

**Comment by propensive** [comment] 2016-01-03 00:22
Sorry about that! It was done for a few of the repositories (e.g. https://github.com/propensive/rapture-json), but not all...

I'll sort it now!

**Comment by PerWiklander** [comment] 2016-01-03 00:37
Thanks! Next thing I found is that there is no released `M2-SNAPSHOT` of
`rapture-i18n_2.11` so using `"com.propensive" %%% "rapture-i18n" % "2.0.0-M2-SNAPSHOT"` in a scala.js shared project breaks.

**Comment by propensive** [comment] 2016-01-03 00:54
All the old repositories (I think) have been updated. This had been on my todo list for a while, so thanks for nudging it!

I'll close this issue and create a new issue for the Scala.js problem.

**Closed as completed by propensive** 2016-01-03 00:54 UTC

**Comment by propensive** [comment] 2016-01-03 01:00
@PerWiklander I've created issue #37 as the root cause of the lack of binaries. You should be able to use 2.0.0-M1, which did successfully build and release. The differences with the M2 release aren't huge, though a few new modules were merged into the M2 release.
